core/urls.py
from django.contrib import admin
from django.urls import path, include
from links.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('links.urls', namespace = "link")),
    # path('register', register),
    path('users/', include('users.urls', namespace = "users")),
]

links/urls.py
from django.urls import path
# from .views import  home
from .views import * 

app_name = "link"

urlpatterns = [
    path("", home, name="home"),
    path("listlar", link_list, name="link_list"),
    path("listlar/create/", link_create, name="link_create"),
    path("listlar/<int:pk>/", link_detail, name="link_detail"),
    path("listlar/<int:pk>/update/", link_update, name="link_update"),
]

links/models.py
from django.db import models

class Link(models.Model):
    name = models.CharField(max_length=50)      # Varchar(50)
    description = models.TextField(null=True)   # varchar(-)
    url = models.URLField(help_text='Iltimos to\'g\ri URL kiriting!')  # Varchar()
    creted_at = models.DateTimeField(auto_now_add = True)   # TIMESTAMP
    modified_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.name


# python manage.py makemigrations
# python manage.py migrate
# python manage.py showmigrations
# python manage.py shell

    # class Meta:


# class LinkChangesHistory(models.Model):
#     link = models.ForeignKey(Link, on_delete=models.CASCADE) # 3
#     name = models.CharField(max_length=50)   # Varchar(50)
#     description = models.TextField(null=True)         # varchar(-)
#     url = models.URLField()                  # Varchar()
#     created_at = models.DateTimeField(auto_now_add=True)      # TIMESTAMP


# Link.objects.all()  -- barcha linklarni olish
# Link.objects.first()  -- tablitsadagi 1-linkni olish
# Link.objects.last()  -- tablitsadagi oxirgi linkni olish
# yangi_link = Link.objects.create(name='', ...)  -- yangi obyekt yaratadi va db ga ham saqlaydi

# python manage.py makemigrations   -->   
# python manage.py migrate   --> 
# python manage.py showmigrations -->
# python manage.py shell  -> django shell ni ochadi

links/forms.py
# from msilib.schema import Error
from django.forms import ValidationError
from django import forms
from .models import Link
# Error()

class LinkForm(forms.ModelForm):

    class Meta:
        model = Link
        fields = ['name', 'description', 'url'] # ('name', 'description', 'url')
    
    # def clean_<field_name>(self):
    #     pass    
    
    def clean_description(self):
        print('clean_date funksiyasi ishga tushdi:', self.cleaned_data)
        description = self.cleaned_data['description'] #yoki self.cleaned_data['description']
        print('description:', description)

        if len(description.split()) < 3:
            raise ValidationError('Izoh kamida 3 ta so\'z bo\'lishi kerak.')
    
        return description

    def clean(self):
        super().clean()
        url_data = self.cleaned_data['url']
        if Link.objects.filter(url = url_data):
            raise ValidationError('Bunday havola allaqachon qo\'shilgan')
        return self.cleaned_data

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=120, required=True, label='Login')
    email = forms.EmailField(max_length=50, initial='example@gmail.com',
             help_text='Iltimos to\'g\'ri email kiriting.')
    password = forms.CharField(max_length=100,
                        widget=forms.PasswordInput(attrs={'class': 'special'}))
    password_confirmation = forms.CharField(max_length=100, widget=forms.PasswordInput)
    description = forms.CharField(max_length=5000, widget=forms.Textarea)

    password_confirmation.widget.attrs.update({'class': 'special'})
    password_confirmation.widget.attrs.update(size='40')

    def clean_password(self):
        parol = self.cleaned_data['password']
        if len(parol) < 7:
            raise ValidationError('Parol kamida 7ta belgidan iborat bo\'lishi lozim')
        if parol.isnumeric():
            raise ValidationError('Parolda kamida bitta harf yoki belgi ishtirok etishi lozim')
        if parol.isalpha():
            raise ValidationError('Parolda kamida bitta raqam ishtirok etishi lozim')
        return parol

    def clean_password_confirmation(self):
        # password = self.cleaned_data['password']
        print(self.data)
        password = self.data['password']
        confirm_password = self.cleaned_data['password_confirmation']
        if password != confirm_password:
            raise ValidationError('Tasdiqlash paroli notogri')
        return confirm_password

    def clean(self):
        data = super().clean() # cleaned_data
        if data['username'] in usernames:
            raise ValidationError('This username is already registered on our platform')
        return data
class MyForm(forms.Form):
    pass   

links/views.py
from .models import Link
from links import models
from django.http import Http404
from django.shortcuts import redirect, render
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404
from .forms import LinkForm, RegisterForm

def home(request):    
    # logic goes here
    # return HttpResponse("<h1>Hello, World!</h1>")
    return render(request, "details/home.html")

def bye(request):
    # logic goes here
    return HttpResponse("<h1>Good Bye, Guys!</h1>")

# def link_list(request):
#     links = Link.objects.all()
#     _html_template = loader.get_template('link_list.html')
#     context = {
#         "title": "Bu sarlavha",
#         "linklar": links
#     }
#     _html = _html_template.render(context, request)
#     return HttpResponse(_html)

def link_list(request):     # list-view
    links = Link.objects.all()  # queryset
    context = {
        "title": "Bu sarlavha",
        "linklar": links
    }
    return render(request, "link/link_list.html", context)   # shortcuts


# def link_detail(request, pk):
#     try:
#         link = Link.objects.get(id=pk)  # get(name="birinchi havola")
#     except Exception as e:
#         print(e)
#         raise Http404('Afsuski siz izlagan link topilmadi!')
#         # return HttpResponse("Afsuski siz izlagan link topilmadi!") # 200 HTTP 

#     return render(request, 'link_detail.html', {'link': link}) # 200 HTTP

def link_detail(request, pk):
    link = get_object_or_404(models.Link, id = pk)
    
    return render(request, "link/link_detail.html", {'link': link})


# def link_create(request):
#     errors = {}
#     data = {}
#     print(f"==========={request.method}===============")
#     if request.method == 'GET':
#         print('bu GET so\'rovi edi. Bunday zaproslar kelganda biror logika boyicha response qaytarish mumkin')
#         print('request.GET=', request.GET) # request.GET  - QueryDict: {} (QueryDictionary)

#     if request.method == 'POST':
#         print(request.POST)
#         link_name = request.POST.get('name')
#         link_description = request.POST.get('description')
#         link_url = request.POST.get('url')
#         data['name'] = link_name
#         data['description'] = link_description
#         data['url'] = link_url
#         # new_link = Link(name=link_name)
#         # new_link.url = link_url
#         # new_link.description = link_description
#         # new_link.image = 'asd'
#         # new_link.save()
#         if link_name and link_url:
#             old_link = Link.objects.filter(name=link_name) # QuerySet [<Link 1>, <Link 2>]
#             if old_link: # old_link.exists()
#                 errors['other'] = 'Bunday nom bilan havola qoshilgan. Iltimos boshqa nom tanlang'
            
#             new_link = Link.objects.create(
#                 name=link_name,
#                 description=link_description,
#                 url=link_url
#             )
#             return redirect('/havolalar/') # domain.nomie/havolalar/
#         else:
#             if not link_name:
#                 errors['name'] = 'Please input link name'
            
#             if not link_url:
#                 errors['url'] = 'Please input link url'

#     return render(request, 'link_create.html', {'errors': errors, 'data': data}) # 200 HTTP

def link_create(request):   
    form = LinkForm()
    
    if request.method == 'POST':
        # request.POST['name']
        form = LinkForm(request.POST) # is_bounded
        # form.is_valid()
        if form.is_valid(): # False
            form.save() # model from
            return redirect('link:link_list')

    return render(request, "link/link_create.html", {'form': form}) # 200 HTTP


def link_update(request, pk):
    link = get_object_or_404(Link, id = pk)
    form = LinkForm(instance=link)

    if request.method == 'POST':
        form = LinkForm(instance=link, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('link:link_list') 

    return render(request, "link/link_update.html", {'form': form})


def register(request):
    form = RegisterForm()
    print('is_boound', form.is_bound)
    print('fields', form.fields)

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        print('data', form.data)
        if form.is_valid():
            pass
        print('cleaned_form', form.cleaned_data)
    return render(request, "link/register.html", {'form': form})

links/templates/link/link_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Link Create{% endblock %}

{% block content%}

<h1 style="text-align:center">Havola qo'shish</h1>
{% comment %} <form action="" method="POST"  class="" id="">
        
  <label for="">Link name:</label> <br>
  <input type="text" name="name" placeholder="link nomini yozing..."
       value="{{data.name}}"    required />
  <small style="color:red;"> {% if errors.name %}{{errors.name}}{% endif %} </small>
  <br><br>

  <label for="">Link description:</label> <br>
  <textarea name="description" placeholder="link haqida izoh.."
      >{{data.description}}</textarea>
  </br><br>
  
  <label for=""> Link url</label> </br>
  <input type="text" name="url" placeholder="link urlini ko'rsating" 
      value="{{data.url}}" required />
  <small style="color:red;"> {% if errors.url %}{{errors.url}}{% endif %} </small>
  
  <br><br>
  
  <input type="submit" value="Yuborish">
  {% csrf_token %}
</form>  {% endcomment %}


<form method="POST"> {% csrf_token %}
  {{form.as_p}}
   
  <input type="submit" value="Yuborish">
</form>

<br>
<a href="{% url 'link:link_list' %}" style="padding: 5px 7px; background: blue; color: white;">
  otrga qaytish
</a>
<p>'Yuborish' tugmasi bosilganda kiritilgan malumotlar
  serverga POST metodi orqali yuboriladi</p>

{% endblock %}

links/templates/link/link_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Link Detail{% endblock %}

{% block content%}

<h1 style="text-align:center">Detail</h1>

<div style="background: lightgray; padding: 10px;">
  <h1>{{link.name}}</h1>
  <p>{{link.description}}</p>
  <a href="{{link.url}}" style="padding: 5px 7px; background: blue; color: white;">
    havolaga o'tish
  </a>
  <hr class="hr">

  <a href="{% url 'link:home' %}" style="padding: 5px 7px; background: blue; color: white;">
    otrga qaytish
  </a>
  <hr class="hr">

  <a href="{% url 'link:link_update' link.pk %}" style="padding: 5px 7px; background: blue; color: white;">
    O'zgartirish
  </a>
  <p> 
    {{ link.creted_at }}
    {% comment %}
      {{ link.creted_at|date:"D d M Y" }}
      {{ link.creted_at|time:"H:i" }}
    {% endcomment %}
  </p>
</div>

{% endblock %}

links/templates/link/link_list.html
{% extends 'base.html' %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'link/css/style.css' %}">
{% endblock %}

{% block title %} Link List {% endblock %}

{% block content%}

<h1 style="text-align:center">Havolalar</h1>

{% for list in linklar %}
<h2 style="padding:10px; background: #808082; border: 1px solid #808080; margin: 5px 500px;">
    <a href="{% url 'link:link_detail' list.pk %}" style="text-decoration: none; color: black;">
        {{list.id}} {{list.name}}
    </a>
</h2>
{% endfor %}
<div class="btn" style="display: flex; justify-content: center;">
    <button style="padding: 4px 8px; border: none; background: blue; margin-right: 4px;">
        <a href="{% url 'link:home' %}" style="text-decoration: none; color: white;">Home</a>
    </button>
    <button style="padding: 4px 8px; border: none; background: blue;">
        <a href="{% url 'link:link_create' %}" style="text-decoration: none; color: white;">link qo'shish</a>
    </button>
</div>
{% endblock %}

links/templates/link/link_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Link Update{% endblock %}

{% block content%}

<h1 style="text-align:center">Havolani taxrirlash</h1>

<form action="" method="POST" class="" id="" enctype="multipart/form-data">
  {{form.as_p}}
  <input type="submit" value="Yuborish">
  {% csrf_token %}
</form>
<br>
<a href="{% url 'link:link_list' %}" style="padding: 5px 7px; background: blue; color: white;">
  otrga qaytish
</a>
<p>'Yuborish' tugmasi bosilganda kiritilgan malumotlar
  serverga POST metodi orqali yuboriladi</p>

{% endblock %}

links/templates/link/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Ro'yxat{% endblock %}

{% block content%}

<h1 style="text-align:center">Ro'yxatdan o'tish</h1>
    
        <h2>Register Form</h2>
        <form method="POST"> 
            
            {% csrf_token %}
            
            <!-- Formadagi umumiy xatoliklar -->
            {% for error in form.non_field_errors %}
                <p style="color:red">{{error}}</p>
            {% endfor %}

            <div class="username">
                {{form.username.label}} <!-- label -->
                {{form.username}}  <!-- input-->

                <!-- Ayni shu inputga tegishli errorlar -->
                {% if form.errors.username %}
                    <small style="color:red;">{{form.errors.username}}</small>
                {% endif %}
            </div>

            <div class="email">
                {{form.email.label}}
                {{form.email}}
            </div>

            <div class="">
                {{form.password.label}}
                {{form.password}}
                
                {% if form.errors.password %}
                    <small style="color:red;">{{form.errors.password}}</small>
                {% endif %}
            </div>

            <div class="">
                {{form.password_confirmation.label}}
                {{form.password_confirmation}}
                
                {% if form.errors.password_confirmation %}
                    <small style="color:red;">
                        {% comment %} {{form.errors.password_confirmation}} {% endcomment %}
                        {% for error in form.errors.password_confirmation  %}
                            {{error}}
                        {% endfor %}
                    </small>
                {% endif %}
            
            </div>

            <div class="">
                {{form.description}}
            </div>
        
            <input type="submit" value="Yuborish">
        
        </form>

        <a href="{% url 'link:link_list' %}" style="padding: 5px 7px; background: blue; color: white;">
            Home page
        </a>


{% endblock %}