core/urls.py
from django.contrib import admin
from django.urls import path, include
from links.views import register

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('links.urls', namespace = "link")),
    # path('register', register),
    path('users/', include('users.urls', namespace = "users")),
]

links/urls.py
from django.urls import path
# from .views import  home
from .views import * 

app_name = "link"

urlpatterns = [
    path("", home, name="home"),
    path("listlar", link_list, name="link_list"),
    path("listlar/create/", link_create, name="link_create"),
    path("listlar/<int:pk>/", link_detail, name="link_detail"),
    path("listlar/<int:pk>/update/", link_update, name="link_update"),
]

users/urls.py
from django.urls import path
from .views import check_user, register, login_view, logout_view, register_view
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView

app_name = "users"

urlpatterns = [
    path('check-user', check_user),
    path('login', LoginView.as_view(), name="login"),
    path('logout', LogoutView.as_view(), name="logout"),
    path('register', register, name="register"),
    path('pass-res', PasswordResetView.as_view(), name="pass_res"),
    path('custom-login', login_view, name="custom_login"),
    path('custom-logout', logout_view, name="custom_logout"),
    path('custom-register', register_view, name="custom_register")
]

templates/details/footer.html
<!-- {% load static %}
<footer >
  <div class="container px-5 py-24 mx-auto flex md:items-center lg:items-start md:flex-row md:flex-nowrap flex-wrap flex-col">
    <div class="w-64 flex-shrink-0 md:mx-0 mx-auto text-center md:text-left">
      <a class="flex title-font font-medium items-center md:justify-start justify-center text-gray-900">
        <img class="w-12" src="{% static 'img/logo.png' %}" alt="">
        <span class="ml-3 text-xl">Havola.uz</span>
      </a>
      <p class="mt-2 text-sm text-gray-500">Air plant banjo lyft occupy retro adaptogen indego</p>
    </div>
    <div class="flex-grow flex flex-wrap md:pl-20 -mb-10 md:mt-0 mt-10 md:text-left text-center">
      <div class="lg:w-1/4 md:w-1/2 w-full px-4">
        <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">CATEGORIES</h2>
        <nav class="list-none mb-10">
          <li>
            <a class="text-gray-600 hover:text-gray-800">First Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Second Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Third Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Fourth Link</a>
          </li>
        </nav>
      </div>
      <div class="lg:w-1/4 md:w-1/2 w-full px-4">
        <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">CATEGORIES</h2>
        <nav class="list-none mb-10">
          <li>
            <a class="text-gray-600 hover:text-gray-800">First Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Second Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Third Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Fourth Link</a>
          </li>
        </nav>
      </div>
      <div class="lg:w-1/4 md:w-1/2 w-full px-4">
        <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">CATEGORIES</h2>
        <nav class="list-none mb-10">
          <li>
            <a class="text-gray-600 hover:text-gray-800">First Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Second Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Third Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Fourth Link</a>
          </li>
        </nav>
      </div>
      <div class="lg:w-1/4 md:w-1/2 w-full px-4">
        <h2 class="title-font font-medium text-gray-900 tracking-widest text-sm mb-3">CATEGORIES</h2>
        <nav class="list-none mb-10">
          <li>
            <a class="text-gray-600 hover:text-gray-800">First Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Second Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Third Link</a>
          </li>
          <li>
            <a class="text-gray-600 hover:text-gray-800">Fourth Link</a>
          </li>
        </nav>
      </div>
    </div>
  </div>
  <div class="bg-gray-100">
    <div class="container mx-auto py-4 px-5 flex flex-wrap flex-col sm:flex-row">
      <p class="text-gray-500 text-sm text-center sm:text-left">© 2022 Havola.uz —
        <a href="https://twitter.com/knyttneve" rel="noopener noreferrer" class="text-gray-600 ml-1" target="_blank">@root8</a>
      </p>
      <span class="inline-flex sm:ml-auto sm:mt-0 mt-2 justify-center sm:justify-start">
        <a class="text-gray-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
            <rect width="20" height="20" x="2" y="2" rx="5" ry="5"></rect>
            <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01"></path>
          </svg>
        </a>
        <a class="ml-3 text-gray-500">
          <svg fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="0" class="w-5 h-5" viewBox="0 0 24 24">
            <path stroke="none" d="M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z"></path>
            <circle cx="4" cy="4" r="2" stroke="none"></circle>
          </svg>
        </a>
      </span>
    </div>
  </div>
</footer> -->

templates/details/home.html
{% extends 'base.html' %}
{% load static %}

{% block css_files %}
<link rel="stylesheet" href="{% static 'link/css/style.css' %}">
{% endblock %}

{% block title %} Home Page {% endblock %}

{% block content%}

<h1 style="text-align:center">Bosh sahiya</h1>
<br>
<ul>
    <li><a href="{% url 'link:link_list' %}" style="padding: 5px 7px; background: blue; color: white;">
        linklar</a>
    </li>
    <br>
    <li><a href="{% url 'users:custom_register' %}" style="padding: 5px 7px; background: blue; color: white;">
        Ro'yxatdan o'tish</a>
    </li><br>
    <li><a href="{% url 'users:login' %}" style="padding: 5px 7px; background: blue; color: white;">
        kirish</a>
    </li>
</ul>
<hr class="hr">
<p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cum, impedit iure aliquam asperiores voluptatum aperiam,
    fugit ut sint nulla quis ipsa quaerat aut. Repellendus id architecto dignissimos corporis beatae adipisci!</p>
{% comment %} <img src="{% static 'img/img1.jpg' %}" alt="" width="100"> {% endcomment %}

{% endblock %}

{% block js_files %}
<script src="{% static 'link/js/script.js' %}"></script>
{% endblock %}

templates/details/navbar.html
{% load static %}

<nav id="header" class="navbar navbar-expand navbar-light bg-white">
  <div class="container d-flex">
    <div class="d-flex justify-content-between w-100">
      <div class="order-1 col-md-2 col-sm-3 col-6">
        <a href="" class="text-decoration-none link-dark align-items-center d-flex navbar-brand w-100">          
          <img src="{% static 'img/havola_logo.svg' %}" class="me-2" alt="" width="26px">
          <span class="w-100"> HAVOLA </span>
        </a>
      </div>
      <div class="order-2 col-md-8 col-sm-6 col-12 d-flex align-items-center">
        <form action="" class="inline-group global-search-div">
          <i class="fa fa-search"></i> 
          <input type="search" name="" id="" placeholder="Izlash">
        </form>
      </div>
      <div class="order-3 col-md-2 col-sm-3 col-6 d-flex align-items-center">
        {% if user.is_authenticated %} 
          user: {{user.first_name}}
          <a href="{% url 'users:logout' %}" style="padding: 5px 7px; background: blue; color: white;">
            chiqish
          </a> 
        {% endif %}
        {% if not user.is_authenticated %}
        <a href="{% url 'users:custom_register' %}" style="padding: 5px 7px; background: blue; color: white;">
          ro'yxatdan o'tish
        </a>
        {% endif %}
      </div>
    </div>
  </div>

</nav>

<!-- -->